apiVersion: v1
kind: ConfigMap
metadata:
  name: ngo-landing-page-config
  labels:
    app: ngo-landing-page
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "base"
  NGINX_WORKER_PROCESSES: "auto"
  NGINX_WORKER_CONNECTIONS: "1024"